import type { IconName } from "@fortawesome/free-solid-svg-icons";

const commonIcons: readonly IconName[] = [
  "home",
  "house-user",
  "faucet",
  "plug",
  "utensils",
  "hamburger",
  "ice-cream",
  "pizza-slice",
  "bread-slice",
  "coffee",
  "cocktail",
  "wine-bottle",
  "wine-glass",
  "gas-pump",
  "car",
  "motorcycle",
  "bicycle",
  "plane",
  "ship",
  "phone",
  "mobile",
  "wifi",
  "medkit",
  "heartbeat",
  "briefcase",
  "ticket-alt",
  "music",
  "film",
  "book",
  "university",
  "piggy-bank",
  "user",
  "hand-holding-heart",
  "random",
  "ban",
  "plus",
  "angle-double-down",
  "angle-double-up",
];

export default commonIcons;
